### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by RollTideDG** [cstrachan88/PoGo-Proxy.NET#3]
I have compiled the proxy in VS2015 and have protoc.exe in my path and it is adding the .cs files to the DecodedProtos

I am using in iPhone so not sure if I am missing a step or not but I extracted the cert (Titanium Root Certificate Authority) from my machine and installed it on my iPhone. I set the proxy settiings on my WI-fi connection.

When I start the game I can see it trying to send a request but it looks like it never finishes or sends to along to niantic. I just get the following twice and then the app says failed login :

[-->] Request to pogo api server (XXXXXXXXXXXXXXXXXX)
 [+] GetPlayer: {}
 [+] GetHatchedEggs: {}
 [+] GetInventory: {"LastTimestampMs":0,"ItemBeenSeen":0}
 [+] CheckAwardedBadges: {}
 [+] DownloadSettings: {"Hash":""}

It never does anything else

**Comment by cstrachan88** [comment]
That's happened to me a couple times. Either the servers are down (which I just checked [here](http://www.mmoserverstatus.com/pokemon_go) and it looks like they are up), or the app cache needs to be reset.

Make sure to completely close the app, and reset then cache. Then trying opening it again with the proxy running. Let me know if that fixes it.

**Comment by RollTideDG** [comment]
Not sure what you mean by app cache? I'm on iPhone. 

I force closed the app and it's still a no-go. When I remove the proxy settings the game loads just fine.

**Comment by cstrachan88** [comment]
Can you pull the latest changes and try it again? I added a few extra logging messages that will help figure out what exactly is going on.

I do get an error where the first call always requests 5 messages, and only gets back 2; however, this doesn't block the proxy and your Pokemon Go app shouldn't be affected (currently working to resolve this).

The differences may be due to the different devices but I don't have an iPhone to debug with. Make sure the app is fully closed before you run the proxy. And the proxy has to be running before you start the app.

**Comment by RollTideDG** [comment]
OK sort of have it working now. 
There is something wrong when it goes to get player data. I have to turn off proxy on my phone let the app load up then turn the proxy back on. Turn wifi off and connect to LTE then turn wifi back on. When I do that since it is already in the game I start getting the messages.
Now the important part. I want to get the IV values for all my pokemon's I have. I see the GetInventory() function coming back with almost every action but the Individual pokemon's in my inventory aren't being sent across. How do I read everything in my inventory??

**Comment by RollTideDG** [comment]
So I added this bit of code into your for loop so you can check the IV's of encountered pokemon's on the map when you click on them.

``` cs
string ResponseType = responsePair.Key.ToString();
if(ResponseType == "Encounter")
{
  Console.WriteLine("" + responsePair.Key);
  Console.WriteLine(" Name : " + ((POGOProtos.Networking.Responses.EncounterResponse)responsePair.Value).WildPokemon.PokemonData.PokemonId);
  Console.WriteLine(" Attack : " + ((POGOProtos.Networking.Responses.EncounterResponse)responsePair.Value).WildPokemon.PokemonData.IndividualAttack);
  Console.WriteLine(" Defense : " + ((POGOProtos.Networking.Responses.EncounterResponse)responsePair.Value).WildPokemon.PokemonData.IndividualDefense);
  Console.WriteLine(" Stamina : " + ((POGOProtos.Networking.Responses.EncounterResponse)responsePair.Value).WildPokemon.PokemonData.IndividualStamina);
  Console.WriteLine(" ");
}
if (ResponseType == "DiskEncounter")
{
  Console.WriteLine("" + responsePair.Key);
  Console.WriteLine(" Name : " + ((POGOProtos.Networking.Responses.DiskEncounterResponse)responsePair.Value).PokemonData.PokemonId);
  Console.WriteLine(" Attack : " + ((POGOProtos.Networking.Responses.DiskEncounterResponse)responsePair.Value).PokemonData.IndividualAttack);
  Console.WriteLine(" Defense : " + ((POGOProtos.Networking.Responses.DiskEncounterResponse)responsePair.Value).PokemonData.IndividualDefense);
  Console.WriteLine(" Stamina : " + ((POGOProtos.Networking.Responses.DiskEncounterResponse)responsePair.Value).PokemonData.IndividualStamina);
  Console.WriteLine(" ");
}
```

I still haven't figured out how to read the pokemon's in my inventory.

**Comment by cstrachan88** [comment]
The GetInventoryResponse returns a delta of your inventory. Since you are turning the proxy off and on, the log probably misses the initial inventory call. See [here](http://pastebin.com/2MZVqq15) (I've sanitized some of the values) for what the initial inventory call should look like.

Since the GetInventoryResponse only gives a delta, all subsequent GetInventoryRequests will return an empty list for the InventoryData unless your inventory has changed:

```
{
  "GetInventory":{
    "Success":true,
    "InventoryDelta":{
      "OriginalTimestampMs":999, // Should be the time of the last Inventory response
      "NewTimestampMs":999,
      "InventoryItems":[ ]
    }
  }
}
```

As far as the issue with the proxy not working initially for you, try this.
- Once you get the proxy working and returning messages, close the app **with the proxy still open**
- Close the proxy once the app has completely shut down
- Reopen the proxy and wait til you see the "Logging at" message
- Reopen the app

---

**P.S.** - Put three backticks on the lines before and after your code to put them in a code block. Also, put the language right after the initial backticks on the same line to get syntax highlighting:

> ```cs
> // csharp code
> ```

**Comment by RollTideDG** [comment]
I was analyzed the requests and the very first thing it does when starting the app is make 5 requests . The issue appears to be I am only getting 2 requests back. 
I get : 

e.ResponseBlock {  Parsed Messages:
{"GetPlayer":{"Success":false,"PlayerData":null},"GetHatchedEggs":{"Success":false,"PokemonId":[],"ExperienceAwarded":[],"CandyAwarded":[],"StardustAwarded":[]}}}  PoGo_Proxy.MessageBlock

This is telling me that GetPlayer is failing from niantic for some reason. That also explains why if I let the app do the initial connection and switch over to proxy it works. So there is a bug or something in GetPlayer somewhere. Do you have any changes that I might not have?

**Comment by cstrachan88** [comment]
Update to the latest commit and see if you are getting the same issue (I also added your suggestion about the encounter IVs). You will see that error message, but it doesn't block the proxy. All following requests should be handled without having to reopen it.

This is what my output looks like:

> Hit any key to stop proxy..
> 
> [+++] Proxy started: listening at 192.168.0.19:61212
> 
> [*] Request messages count (5) is different than the response messages count (2).
> Request:
> {"MessageInitialized":"2016-07-22T11:12:24.1705257-07:00","ParsedMessages":{"GetPlayer":{},"GetHatchedEggs":{},"GetInventory":{"LastTimestampMs":0,"ItemBeenSeen":0},"CheckAwardedBadges":{},"DownloadSettings":{"Hash":""}}}
> Response:
> Not sure yet how to read this without knowing what it is.
> [*]
> 
> Response blocks:
>   GetPlayer
>   GetHatchedEggs
> 
> Response blocks:
>   GetPlayer
>   GetHatchedEggs
>   GetInventory
>   CheckAwardedBadges
>   DownloadSettings
> 
> Response blocks:
>   GetPlayer
>   GetHatchedEggs
>   GetInventory
>   CheckAwardedBadges
>   DownloadSettings
> 
> Response blocks:
>   ...

**Comment by RollTideDG** [comment]
Whatever you did I can get my Inventory now. 

it is still failing at the beginning with received 2 responses and expected 5 but it's not keeping the game from loading now.

**Comment by cstrachan88** [comment]
Good! Glad it's working for you now. Those messages will be fixed in just a sec. Pulling some final things together.

**Comment by RollTideDG** [comment]
You wouldn't happen to have a code snippet that dumps that inventory out to like a CSV file or anything would you?
