### ISSUE TITLE
Doesn't seem to get inital data

### ISSUE THREAD

**Issue by TheTravelingTrainer** [cstrachan88/PoGo-Proxy.NET#6]
Thanks for the work so far. 

I've only used the proxy since the new update, i've removed the ssl pinning , but I've noticed I don't seem to get the first list of pokemon or the inital items list. 

All map data etc comes through fine. 

I removed the sample and tried logging the results at the OnResponce event. But still get everything except them inital list.

Is there a bug / something im missing, I've tried clearing the cache on the phone. But still seems to never get sent the item / pokemon list data. 

Also I notice if I run a bot/api through it, i'll see all the item data, but they request it frequently.

Could the initial data come from something other than the niatnic servers? 

Don't suppose you could shed some light on the issue? :)

**Comment by cstrachan88** [comment]
Hey, I've been travelling over the last week so I've been unable to get back to this. I'll have time after Thursday so unfortunately I won't be much help til then.

From the logs I have before the .31 update, the initial handshake is returning the first inventory response:

``` json
{
  "RequestBlock": {
    "MessageInitialized": "...",
    "ParsedMessages": {
      "GetPlayer": {},
      "GetHatchedEggs": {},
      "GetInventory": {
        "LastTimestampMs": 0,
        "ItemBeenSeen": 0
      },
      "CheckAwardedBadges": {},
      "DownloadSettings": {
        "Hash": ""
      }
    }
  },
  "ResponseBlock": {
    "MessageInitialized": "...",
    "ParsedMessages": {
      "GetPlayer": {
        "..."
      },
      "GetHatchedEggs": {
        "..."
      },
      "GetInventory": {
        "Success": true,
        "InventoryDelta": {
          "OriginalTimestampMs": 0,
          "NewTimestampMs": 999,
          "InventoryItems": [
            * "Initial inventory response here" *
          ]
        }
      },
      "CheckAwardedBadges": {
        "Success": true,
        "AwardedBadges": [],
        "AwardedBadgeLevels": []
      },
      "DownloadSettings": {
        "..."
      }
    }
  }
}
```

If I recall, I changed how I was handling the initial handshake message. I may have taken it out of the responses that get sent to the log. I can confirm later today once I get off my flight, but that would be where I would suggest looking.

**Comment by TheTravelingTrainer** [comment]
Yeah what you've said is exactly what I was expecting.

But for some the first GetMapObjects envlope that gets sent from the client donen't seem to have a Timestamp set to 0 for GetInvetoryItems.

This is my first GetInvetoryItem call from the client:

```
    "GetInventory": {
      "LastTimestampMs": 1470704795491, << Would expect first call to be 0....
      "ItemBeenSeen": 0
```

I feel like I must be missing something... Driving me mad! ha.

**Comment by TheTravelingTrainer** [comment]
Sent Request:
OUT: GetPlayer
Got Responce:
In packet length:148
RequestID:6032429073588813826
IN: GetPlayer SIZE: 0
bootstrap.upsight-api.com
In packet length2:2280
android.clients.google.com
In packet length2:146
single.upsight-api.com
In packet length2:47
Sent Request:
OUT: GetMapObjects
OUT: GetHatchedEggs
OUT: GetInventory << this is the first one... But already had a timestamp set, instead of expected 0
OUT: CheckAwardedBadges
OUT: DownloadSettings
Got Responce:
In packet length:3201
RequestID:7194579732770324486
IN: GetMapObjects SIZE: 3101 <<< What i expect
IN: GetHatchedEggs SIZE: 2
IN: GetInventory SIZE: 18 <<< See too small
IN: CheckAwardedBadges SIZE: 2
IN: DownloadSettings SIZE: 42
[+] New GetHatchedEggs response
    No hatched eggs

[+] New GetInventory response
    lots of data to parse

[+] New CheckAwardedBadges response
    No awarded badges
